### ISSUE TITLE
updateComment Feedback

### ISSUE THREAD

**Issue by jordanwillis** [dimces/the-scoop#1]
Nice work on everything so far.  As I was reviewing your `updateComment` function it looks like you are not ever actually saving the updated comment to the database.  When I did a quick test with the front end, the results I got matched my assumptions (e.g. the comment did not update).

Take a look at this line.

https://github.com/dimces/the-scoop/blob/master/server.js#L302

It looks like you might have mistakenly put the assignment in the wrong order?  At any rate, since you have already looked up the previously saved comment in line 293, all you need to do is...

`savedComment.body = requestComment.body || savedComment.body;`

Which saves the updated comment from the request, or if by some chance the request did not contain a comment (your logic is already checking for this case but might as well be extra sure), then the previous comment will be used.

**Comment by dimces** [comment]
Thanks for pointing out, i fixed it.
