### ISSUE TITLE
deleteComment feedback

### ISSUE THREAD

**Issue by jordanwillis** [dimces/the-scoop#2]
Watch out when trying to delete the comment id from the users and articles comments list.  You have the right approach but re-think about the first argument you are passing to `splice()`

https://github.com/dimces/the-scoop/blob/master/server.js#L322

`savedComment` is an object and not an index and `splice` is expecting to receive a start index as the first argument.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

When I tested the delete from the UI, the comment itself did successfully delete (which your logic is doing correctly), however errors were thrown if I tried to view the articles comments again (because of the faulty logic).

Instead, you need to use `savedComment` to lookup the comment ids in the users and articles collections and then find the index of comment to be deleted using `indexOf()`

```
const userCommentIds = database.users[savedComment.username].commentIds;
userCommentIds.splice(userCommentIds.indexOf(id), 1);

const userArticleIds = database.articles[savedComment.articleId].commentIds;
userArticleIds.splice(userArticleIds.indexOf(id), 1);
```

**Comment by dimces** [comment]
Thanks for pointing out, i fixed it.
