### ISSUE TITLE
Summary: Grade = Meets Expectations

### ISSUE THREAD

**Issue by jordanwillis** [dimces/the-scoop#3]
Overall you did a great job on this project!  I liked how you were able to implement a (mostly) working API from a set of written specifications.  Take a look at the couple issues that I found and if you have time, I would recommend reviewing the provided testing code to see if the tests inadequately test that logic.  This would be a good exercise because all of the test cases did in fact pass, so it just goes to show that implementing the testing of even a small and simple API can be a challenge.

I would also recommend that you attempt the extra credit if you have time.  It turns out, with the help of a node package called `node-yaml`, the implementation of `saveDatabase()` and `loadDatabase()` can be done in only a few lines of code.

Keep up the good work!

**Comment by dimces** [comment]
Thanks very much for feedback.
